### ISSUE TITLE
Error for Launch /!\

### ISSUE THREAD

**Issue by PentestinGxRoot** [maaaaz/CrackMapExecWin#3]
OS: WINDOWS 10
ALL NECESSARY TOOL UPDATE AND INSTALL

```

C:\Palma\CMS\cme>python crackmapexec.py
Traceback (most recent call last):
  File "crackmapexec.py", line 5, in <module>
    from cme.logger import setup_logger, setup_debug_logger, CMEAdapter
  File "C:\Python27\lib\site-packages\crackmapexec-4.0.1.dev0-py2.7.egg\cme\__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
WindowsError: [Error 3] Le chemin dÆaccÞs spÚcifiÚ est introuvable: 'C:\\Python27\\lib\\site-packages\\crackmapexec-4.0.1.dev0-py2.7.egg\\cme\\thirdparty/*.*'
```

C:\Palma\CMS\cme>

**Comment by maaaaz** [comment]
Hello, 

Sorry but I am not the maintainer of `CrackMapExec`.
You have to report your bug there : https://github.com/byt3bl33d3r/CrackMapExec/issues/

Cheers.
