### ISSUE TITLE
issue when running with '-H' option (NTLM hash)

### ISSUE THREAD

**Issue by syriusbughunt** [maaaaz/CrackMapExecWin#7]
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 327, in run
  File "Z:\Partage\CrackMapExec_fork\core\maingreenlet.py", line 65, in connect
  File "Z:\Partage\CrackMapExec_fork\core\smartlogin.py", line 133, in smart_log
in
ValueError: need more than 1 value to unpack
<Greenlet at 0x3155800: connect('10.1.1.60')> failed with ValueError
```

The original command is:

crackmapexec.exe ips.txt -u Administrator -H dc4d7e10165620d32f901d915065c93d -t 5

**Comment by maaaaz** [comment]
Hello @syriusbughunt,
I really don't know, if you try without the `-t` option and add some verbosity ?

**Comment by derekkddj** [comment]
i have the same problem

**Comment by maaaaz** [comment]
And with a ":" before the hash ?
Like this `-H :dc4d7e10165620d32f901d915065c93d` ?
